---
# Enable modules.
- name: Enable general modules
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: global.modules

- name: Enable default environment modules
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: default_env.modules
  when: pp_environment == "default"

- name: Enable demo environment modules
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: demo_env.modules
  when: pp_environment == "demo"

- name: Enable staging environment modules
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: staging_env.modules
  when: pp_environment == "staging"

- name: Enable production environment modules
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: production_env.modules
  when: pp_environment == "production"

# Drush commands.
- name: Run general drush commands
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: global.drush_commands

- name: Run drush commands for default environment
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: default_env.drush_commands
  when: pp_environment == "default"

- name: Run drush commands for demo environment
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: demo_env.drush_commands
  when: pp_environment == "demo"

- name: Run drush commands for staging environment
  shell: "{{ php_env_vars }} drush -y en {{ item }}"
  with_items: staging_env.drush_commands
  when: pp_environment == "staging"

- name: Run drush commands for production environment
  shell: "{{ php_env_vars }} drush -y {{ item.name }} {{ item.arguments }}"
  with_items: production_env.drush_commands
  when: pp_environment == "production"

# Update admin username and password.
- name: Update admin username
  sudo: yes
  shell: drush sqlq "UPDATE users SET name='{{ drupal_user }}' WHERE uid=1"
  when: update_admin_user == true and (pp_environment == "default" or pp_environment == "demo")

- name: Update admin password
  sudo: yes
  shell: "{{ php_env_vars }} drush user-password {{ drupal_user }} --password={{ drupal_pass }}"
  when: update_admin_user == true and (pp_environment == "default" or pp_environment == "demo")
