---
- name: Making permissions usable
  shell: chmod -R 777 sites/default
  sudo: yes

- name: Check if registry_rebuild is installed
  shell: "{{ php_env_vars }} drush | grep -c registry_rebuild"
  register: registry_rebuild_installed
  ignore_errors: true

- name: Downloading registry_rebuild
  sudo: yes
  shell: "{{ php_env_vars }} drush -y dl registry_rebuild"
  when: workflow_type == "sql" and registry_rebuild_installed.stdout == "0"

- name: Clear drush cache
  sudo: yes
  shell: "{{ php_env_vars }} drush cc drush"
  when: workflow_type == "sql" and registry_rebuild_installed.stdout == "0"

- name: Rebuilding drupal registry
  sudo: yes
  shell: "{{ php_env_vars }} drush -y rr -l {{ site_url }} || true"
  when: workflow_type == "sql"

- name: Updating database
  sudo: yes
  shell: "{{ php_env_vars }} drush -dvy updb -l {{ site_url }}"
  when: workflow_type == "sql"

- name: Enable module Stage File Proxy
  sudo: yes
  shell: "{{ php_env_vars }} drush -y en stage_file_proxy"
  when: pp_environment == "demo" or pp_environment == "default"

- name: Creating latest staging backup
  sudo: yes
  mysql_db: name=staging state=dump target={{ backup_folder }}/latest.sql.gz login_user={{ mysql_user }} login_password={{ mysql_pass }}
  when: make_backup == true and pp_environment == "staging" or make_backup

- name: Solr - clearing index
  sudo: yes
  shell: "{{ php_env_vars }} drush -y search-api-clear -l {{ site_url }}"
  when: pp_environment == "CHANGE_ME"

- name: Solr - reindexing
  sudo: yes
  shell: "{{ php_env_vars }} drush -y search-api-index -l {{ site_url }}"
  when: pp_environment == "CHANGE_ME"

- name: Error messages to display settings
  sudo: yes
  shell: "{{ php_env_vars }} drush vset error_level 2"
  when: pp_environment == "default"

- name: Set writable files dir
  sudo: yes
  file: dest=sites/default/files mode=777 state=directory
