---
- name: Enable module Stage File Proxy
  sudo: yes
  shell: "{{ php_env_vars }} drush -y en stage_file_proxy"
  when: pp_environment == "demo" or pp_environment == "default"

- name: Solr - clearing index
  sudo: yes
  shell: "{{ php_env_vars }} drush -y search-api-clear -l {{ site_url }}"
  when: pp_environment == "CHANGE_ME"

- name: Solr - reindexing
  sudo: yes
  shell: "{{ php_env_vars }} drush -y search-api-index -l {{ site_url }}"
  when: pp_environment == "CHANGE_ME"

- name: Update admin username
  sudo: yes
  shell: drush sqlq "UPDATE users SET name='{{ drupal_user }}' WHERE uid=1"
  when: update_admin_user == true and (pp_environment == "default" or pp_environment == "demo")

- name: Update admin password
  sudo: yes
  shell: "{{ php_env_vars }} drush user-password {{ drupal_user }} --password={{ drupal_pass }}"
  when: update_admin_user == true and (pp_environment == "default" or pp_environment == "demo")
