---
- name: Remove settings.php
  file: name=sites/default/settings.php state=absent
  sudo: yes

- name: Creating settings.php
  sudo: yes
  shell: "cp sites/default/default.settings.php sites/default/settings.php"

- name: Adding database variable to settings.php
  sudo: yes
  lineinfile: dest='sites/default/settings.php' line='$databases = array(\"default\" => array (\"default\" => array (\"database\" => \"{{ mysql_db }}\", \"username\" => \"{{ mysql_user }}\", \"password\" => \"{{ mysql_pass }}\", \"host\" => \"127.0.0.1\", \"port\" => \"\", \"driver\" => \"mysql\", \"prefix\" => \"\", ), ), );'

- name: Add general settings to settings.php
  lineinfile: dest='sites/default/settings.php' line='{{ item.name }} = \"{{ item.value }}\";'
  with_items: settings

- name: Add settings for default environment
  lineinfile: dest='sites/default/settings.php' line='{{ item.name }} = \"{{ item.value }}\";'
  with_items: default_env_settings
  when: pp_environment == "default"

- name: Add settings for demo environment
  lineinfile: dest='sites/default/settings.php' line='{{ item.name }} = \"{{ item.value }}\";'
  with_items: demo_env_settings
  when: pp_environment == "demo"

- name: Add settings for staging environment
  lineinfile: dest='sites/default/settings.php' line='{{ item.name }} = \"{{ item.value }}\";'
  with_items: staging_env_settings
  when: pp_environment == "staging"

- name: Add settings for production environment
  lineinfile: dest='sites/default/settings.php' line='{{ item.name }} = \"{{ item.value }}\";'
  with_items: production_env_settings
  when: pp_environment == "production"
