---
# This playbook should be executed using reinstall.sh script
# Developed for ansible version >= 1.7
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - devops/includes/vars/reinstall_vars.yml

  tasks:
  - include: devops/includes/reinstall/database_backup.yml
    when: make_backup
    tags: [ 'backup' ]

  - include: devops/includes/reinstall/pre_install_tasks.yml
    tags: [ 'pre-tasks' ]

  - include: devops/includes/reinstall/sql_workflow.yml
    when: workflow_type == "sql"
    tags: [ 'sql-workflow' ]

  - include: devops/includes/reinstall/profile_workflow.yml
    when: workflow_type == "profile"
    tags: [ 'profile-workflow' ]

  - include: devops/includes/reinstall/settings_windows.yml
    when: is_windows == true
    tags: [ 'windows-settings' ]

  - include: devops/includes/reinstall/settings.yml
    when: is_windows == false
    tags: [ 'settings' ]

  - include: devops/includes/reinstall/post_install_tasks.yml
    tags: [ 'post-tasks' ]
