---
# This playbook should be executed using reinstall.sh script
# Developed for ansible version >= 1.7
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - devops/vars/reinstall_vars.yml

  tasks:
  - include: devops/includes/reinstall/pre_install_tasks.yml
  # @todo Should be by condition.
  - include: devops/includes/reinstall/database_workflow.yml
  # @todo Should be by condition.
  - include: devops/includes/reinstall/profile_workflow.yml
  - include: devops/includes/reinstall/settings.yml
  - include: devops/includes/reinstall/post_install_tasks.yml
